const  items = [
    {  
        id: 1,
        img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
        title: "Nike Air Monarch IV",
        reviews: "(123 reviews)",
        prevPrice: "Rs.1000",
        newPrice: "900",
        company: "Nike",
        color: "white",
        category: "shoes",
        quantity: 1,
    },
    { 
        id: 2,
        img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
        title: "Nike Air Vapormax Plus",
        reviews: "(123 reviews)",
        prevPrice: "Rs.1000",
        newPrice: "900",
        company: "Nike",
        color: "red",
        category: "shoes",
        quantity: 1,
    },

    {   
        id: 3,
        img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
        title: "Nike Waffle One Sneaker",
        reviews: "(123 reviews)",
        prevPrice: "Rs.800",
        newPrice: "600",
        company: "Nike",
        color: "white",
        category: "shoes",
        quantity: 1,
    },
    {
        id: 4,
        img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
        title: "Nike Running Shoe",
        reviews: "(123 reviews)",
        prevPrice: "Rs.600",
        newPrice: "400",
        company: "Nike",
        color: "black",
        category: "shoes",
        quantity: 1,
    },
    {
        id: 5,
        img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
        title: "Vans flat Slip On Pumps",
        reviews: "(123 reviews)",
        prevPrice: "Rs.800",
        newPrice: "600",
        company: "Vans",
        color: "white",
        category: "shoes",
        quantity: 1,
    },
    {
        id: 6,
        img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
        title: "Vans Knit Ballet Flat",
        reviews: "(123 reviews)",
        prevPrice: "Rs.1000",
        newPrice: "900",
        company: "Vans",
        color: "black",
        category: "shoes",
        quantity: 1,
    },

    {
        id: 7,
        img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
        title: "Vans Loafer Flats",
        reviews: "(123 reviews)",
        prevPrice: "Rs.600",
        newPrice: "400",
        company: "Vans",
        color: "white",
        category: "shoes",
        quantity: 1,
    },

    {
        id: 8,
        img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
        title: "Nike Zoom Freak",
        reviews: "(123 reviews)",
        prevPrice: "Rs.800",
        newPrice: "600",
        company: "Nike",
        color: "white",
        category: "shoes",
        quantity: 1,
    },

    {
        id: 9,
        img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
        title: "Puma Men's Sneaker",
        reviews: "(123 reviews)",
        prevPrice: "Rs.600",
        newPrice: "400",
        company: "Puma",
        color: "white",
        category: "shoes",
        quantity: 1,
    },

    {
        id: 10,
        img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
        title: "Puma BLACK-OCE",
        reviews: "(123 reviews)",
        prevPrice: "Rs.800",
        newPrice: "600",
        company: "Puma",
        color: "white",
        category: "shoes",
        quantity: 1,
    },
    {
        id: 11,
        img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
        title: "Puma Pacer Future Sneaker",
        reviews: "(123 reviews)",
        prevPrice: "Rs.800",
        newPrice: "600",
        company: "Puma",
        color: "red",
        category: "shoes",
        quantity: 1,
    },
    {
        id: 12,
        img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
        title: "Puma Unisex-Adult Super",
        reviews: "(123 reviews)",
        prevPrice: "Rs.1000",
        newPrice: "900",
        company: "Puma",
        color: "black",
        category: "shoes",
        quantity: 1,
    },
    {
        id: 13,
        img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
        title: "Puma Basic Sneaker",
        reviews: "(123 reviews)",
        prevPrice: "Rs.800",
        newPrice: "600",
        company: "Puma",
        color: "white",
        category: "shoes",
        quantity: 1,
    },
    {
        id: 14,
        img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
        title: "Puma Pacer Future Doubleknit",
        reviews: "(123 reviews)",
        prevPrice: "Rs.600",
        newPrice: "400",
        company: "Puma",
        color: "black",
        category: "shoes",
        quantity: 1,
    },

    {
        id: 15,
        img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
        title: "Puma Fusion Evo Golf Shoe",
        reviews: "(123 reviews)",
        prevPrice: "Rs.800",
        newPrice: "600",
        company: "Puma",
        color: "white",
        category: "shoes",
        quantity: 1,
    },
    {
        id: 16,
        img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
        title: "Puma Rainbow Chex Skate",
        reviews: "(123 reviews)",
        prevPrice: "Rs.800",
        newPrice: "600",
        company: "Puma",
        color: "red",
        category: "shoes",
        quantity: 1,
    },
    {
        id: 17,
        img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
        title: "Nike Low-Top Trainers",
        reviews: "(123 reviews)",
        prevPrice: "Rs.600",
        newPrice: "400",
        company: "Nike",
        color: "white",
        category: "shoes",
        quantity: 1,
    },
    {
        id: 18,
        img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
        title: "Vans Unisex Low-Top",
        reviews: "(123 reviews)",
        prevPrice: "Rs.1000",
        newPrice: "900",
        company: "Vans",
        color: "white",
        category: "shoes",
        quantity: 1,
    },
    {
        id: 19,
        img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
        title: "Puma Classic Bandana Sneakers",
        reviews: "(123 reviews)",
        prevPrice: "Rs.1000",
        newPrice: "900",
        company: "Puma",
        color: "black",
        category: "shoes",
        quantity: 1,
    },
    {
        id: 20,
        img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
        title: "Vans Chunky High Heel",
        reviews: "(123 reviews)",
        prevPrice: "Rs.600",
        newPrice: "400",
        company: "Vans",
        color: "black",
        category: "heels",
        quantity: 1,
    },
    {
        id: 21,
        img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
        title: "Vans Slip On Stiletto High Heel",
        reviews: "(123 reviews)",
        prevPrice: "Rs.800",
        newPrice: "600",
        company: "Vans",
        color: "black",
        category: "heels",
        quantity: 1,
    },
    {
        id: 22,
        img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
        title: "DREAM PAIRS Court Shoes",
        reviews: "(123 reviews)",
        prevPrice: "Rs.1000",
        newPrice: "900",
        company: "Vans",
        color: "red",
        category: "heels",
        quantity: 1,
    },
    {
        id: 23,
        img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
        title: "Vans Low Mid Block Heels",
        reviews: "(123 reviews)",
        prevPrice: "Rs.1000",
        newPrice: "900",
        company: "Vans",
        color: "black",
        category: "heels",
        quantity: 1,
    },
    {
        id: 24,
        img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
        title: "Vans Chunky High Heel",
        reviews: "(123 reviews)",
        prevPrice: "Rs.600",
        newPrice: "400",
        company: "Vans",
        color: "black",
        category: "heels",
        quantity: 1,
    },
    {
        id: 25,
        img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
        title: "Vans Amore Fashion Stilettos",
        reviews: "(123 reviews)",
        prevPrice: "Rs.600",
        newPrice: "400",
        company: "Vans",
        color: "white",
        category: "heels",
        quantity: 1,
    },
    {
        id: 26,
        img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
        title: "Vans Bridal Sandals Glitter",
        reviews: "(123 reviews)",
        prevPrice: "Rs.800",
        newPrice: "600",
        company: "Vans",
        color: "black",
        category: "heels",
        quantity: 1,
    },
    {
        id: 27,
        img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
        title: "Vans Wedding Prom Bridal",
        reviews: "(123 reviews)",
        prevPrice: "Rs.600",
        newPrice: "400",
        company: "Vans",
        color: "black",
        category: "heels",
        quantity: 1,
    },
    {
        id: 28,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfJVSXvcsWmQmDeQ3Ni1V1dtVrbsks_x2lIA&s",
        title: "Vans Black Sneakers",
        reviews: "(123 reviews)",
        prevPrice: "Rs.600",
        newPrice: "400",
        company: "Vans",
        color: "black",
        category: "shoes",
        quantity: 1,
    },
    {
        id: 29,
        img: "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_300,h_300/global/310197/01/sv02/fnd/IND/fmt/png/Deviate-NITRO%E2%84%A2-Elite-3-Marathon-Series-Men's-Running-Shoes",
        title: "Puma Running Shoes",
        reviews: "(123 reviews)",
        prevPrice: "Rs.800",
        newPrice: "600",
        company: "Puma",
        color: "white",
        category: "shoes",
        quantity: 1,
    },
    {
        id: 30,
        img: "https://m.media-amazon.com/images/I/51B-t5tfcVL._AC_SR175,263_QL70_.jpg",
        title: "Puma Uber Collection Shoes",
        reviews: "(123 reviews)",
        prevPrice: "Rs.1000",
        newPrice: "900",
        company: "Puma",
        color: "black",
        category: "Shoes",
        quantity: 1,
    },
    {
        id: 31,
        img: "https://brand.assets.adidas.com/image/upload/APAC_SEA_IWP_Thumbnails_Shoes_DT_144b7c46b7.jpg",
        title: "Adidas Fall Collection",
        reviews: "(123 reviews)",
        prevPrice: "Rs.1000",
        newPrice: "900",
        company: "Adidas",
        color: "White",
        category: "Shoes",
        quantity: 1,
    },
    {
        id: 32,
        img: "https://i.pinimg.com/736x/4f/1c/f5/4f1cf5a40ba02e136ff11b0cfb8e085e.jpg",
        title: "Adidas Jeremy Forum Wings",
        reviews: "(123 reviews)",
        prevPrice: "Rs.1000",
        newPrice: "900",
        company: "Adidas",
        color: "White",
        category: "Shoes",
        quantity: 1,
    }
    
]

module.exports = items;